### PR TITLE
add link to docs in create polaris help; edit help texts

### LINKED ISSUE #1076: put link to the help docs in synopsysctl
**What would you like to be added**:
put a permanent link to the help docs in synopsysctl

### PR DESCRIPTION
**Pull request by yashbhutwala**
- [x] Add link to create polaris help (closes #1076)
- [x] update version to match what we will be releasing [`2019.11`]
- [x] add an example showing all required flags for recommended setup with external flag
- [x] help text edit

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1107#" title="Author self-approved">yashbhutwala</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/release-2019.11.x/OWNERS)~~ [yashbhutwala]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yashbhutwala** [comment]
What this looks like:

image

**Comment by yashbhutwala** [comment]
Ready to be reviewed and merged 😃

**Comment by operator-r2d2** [comment]
@yashbhutwala: new pull request created: #1108

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/1107#issuecomment-557198117):

>/cherry-pick master


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
