### PR TITLE
update go mods for master

### PR DESCRIPTION
**Pull request by yashbhutwala**
- [x] for ui, update to go 1.13
- [x] run go mod tidy for operator and operator-ui

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1111#" title="Author self-approved">yashbhutwala</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [yashbhutwala]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yashbhutwala** [comment]
Not merging this to 2019.11 release

**Comment by yashbhutwala** [comment]
Tested the ui with this change on top of release branch, works fine.

/cherry-pick release-2019.11.x

**Comment by operator-r2d2** [comment]
@yashbhutwala: #1111 failed to apply on top of branch "release-2019.11.x":
```Applying: for ui, update to go 1.13; run go mod tidy for operator and operator-ui
error: Failed to merge in the changes.
Using index info to reconstruct a base tree...
M	cmd/operator-ui/go.mod
Falling back to patching base and 3-way merge...
Auto-merging cmd/operator-ui/go.mod
CONFLICT (content): Merge conflict in cmd/operator-ui/go.mod
Patch failed at 0001 for ui, update to go 1.13; run go mod tidy for operator and operator-ui

```

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/1111#issuecomment-557593617):

>Tested the ui with this change on top of release branch, works fine.
>
>/cherry-pick release-2019.11.x


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
