### PR TITLE
Fix BlackDuck PVC Issues: Solr and "-"

### PR DESCRIPTION
**Pull request by mphammer**
Issue 1) Black Duck no longer supports solr
Issue 2) "-" should not precede PVC names in mock mode

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1081#" title="Author self-approved">mphammer</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/release-2019.11.x/OWNERS)~~ [mphammer]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yashbhutwala** [comment]
Can you verify whether this commit needs to be reverted: https://github.com/blackducksoftware/synopsys-operator/pull/1060 .  The approaches seem different.  Are we abandoning 10.x branch?  It's fine in that case, but please confirm 😄

**Comment by mphammer** [comment]
> Can you verify whether this commit needs to be reverted: #1060 . The approaches seem different. Are we abandoning 10.x branch? It's fine in that case, but please confirm 😄

It's the same fix. It looks different because in this PR I refactored the functions to make them modular so that I could make tests. 10.x branch is out so we are just putting it into the next release.

**Comment by yashbhutwala** [comment]
@mphammer ideally we shouldn't be adding anything to previous branches if we're not using them (in case we want to have a 10.1 release and keep using the release-10.x branch).  Also, can you make sure, we're cherry-picking changes like this to master 😉 

/cherrypick master

**Comment by operator-r2d2** [comment]
@yashbhutwala: new pull request created: #1091

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/1081#issuecomment-555728483):

>@mphammer ideally we shouldn't be adding anything to previous branches if we're not using them (in case we want to have a 10.1 release and keep using the release-10.x branch).  Also, can you make sure, we're cherry-picking changes like this to master 😉 
>
>/cherrypick master


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
