### PR TITLE
break mod file into pinned down dependencies, and indirect dependencies

### PR DESCRIPTION
**Pull request by yashbhutwala**
/assign @rrati @msenmurugan I tried to simplify the mod file here a bit by breaking it into direct and indirect dependencies.  Hopefully, this makes it cleaner, and more maintainable.  So, the future workflow to update dependencies would be to run `go get -u && go mod tidy && go build ./cmd/... ./pkg/...`;  any updates to `direct dependencies` would go in direct dependency `require` block, and also pinned down in `replace` block.  And `indirect dependencies` would go in the indirect dependency `require` block.  What do you think?

p.s. @rrati also just noticed new `horizon` release but in this pr, i've kept it pinned to what it was before, let me know if I should update it to latest?

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/555#" title="Author self-approved">yashbhutwala</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [yashbhutwala]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rrati** [comment]
@yashbhutwala Couple of questions:

1) if an dependency is updated, will the updated values automatically be in the require block the dep was originally included in or will it be moved to a common require block?  IE, will we be constantly having to keep these separated or will the updates keep these things separated?

2) I'm on the fence about whether we need to lock down indirect deps too.  An update to an indirect dep could affect the operator of our dep.  It isn't clear that module owners are doing semantic versioning as go modules prefers, and we certainly aren't referencing specific versions in our includes.

**Comment by yashbhutwala** [comment]
Answer to 1: Currently `go mod` is not smart enough to recognize difference between two separate `require` blocks, direct and indirect, so it would randomly add it to one of the require blocks, and we'd have to manually edit it 😞.  It will not move it to a common requirement block, which is good so changes would be easily noticed.

Answer to 2: You are correct, maybe we want to lock down all dependencies, but that just means we have to know any changes that are happening to all those dependencies before being able to update to the newer versions.  

If we want to maintain control over what versions of dependencies we use, generally it seems the process will have to be manual.  I hope a better tooling/best practices develops around using `go mod`, but haven't been able to find any right now.

**Comment by yashbhutwala** [comment]
Closing this because other communities are not using this style, will wait till golang has better mod tooling.  But, definitely needs another PR to fix that operator-ui is pulled as a dependency for the main go mod file (circular dependency): https://github.com/blackducksoftware/synopsys-operator/blob/master/go.mod#L9

**Pull request closed without merging**
