### PR TITLE
revert Black Duck 2019.12.1 change and add support for Black Duck 2019.10.3

### PR DESCRIPTION
**Pull request by msenmurugan**
revert Black Duck 2019.12.1 change and add support for Black Duck 2019.10.3

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1214#" title="Author self-approved">msenmurugan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/release-2019.12.x/OWNERS)~~ [msenmurugan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1214#issuecomment-583497068" title="LGTM">mphammer</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1214#" title="Author self-approved">msenmurugan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/release-2019.12.x/OWNERS)~~ [mphammer,msenmurugan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yashbhutwala** [comment]
Just curious, is `2019.12.1` no longer gonna be a thing?  If it is gonna be a release, is `2019.12.1` == `2019.10.2+2019.10.3`?

**Comment by yashbhutwala** [comment]
Follow-up question based on discussion with @Michael Hammer:  Is `2019.12.1` gonna be released at the same time as `2019.10.3`?  If not, why not?

**Comment by yashbhutwala** [comment]
public version of `2019.12.1` will be released after public `2019.10.3` release.  Risks were discussed with @msenmurugan, @mattfenwick and Pat Centralla.  Decision was made by hub/legal team that this is fine.

**Comment by operator-r2d2** [comment]
@msenmurugan: new pull request created: #1215

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/1214#issuecomment-583572273):

>/cherrypick saas-2019.12.1


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by msenmurugan** [comment]
resolves #1220

**Pull request merged**
