### PR TITLE
updated the correct version of nginx and upload cache for Black Duck 2020.2.1

### LINKED ISSUE #1306: Black Duck upload cache is not working
**What happened**:
Black Duck upload cache is not working

**What you expected to happen**:
The files need to be upload for snippet matching and show the file while looking for the difference

**How to reproduce it (as minimally and precisely as possible)**:
Install Black Duck 2020.2.1 Black Duck and run a snippet matching

**Screenshots/additional context**:

**Environment (please complete the following information):**
- Kubernetes version (use `kubectl version`):
- Openshift version (use `oc version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by msenmurugan**
resolves #1306

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1307#" title="Author self-approved">msenmurugan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/release-2020.2.x/OWNERS)~~ [msenmurugan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mphammer** [comment]
This change should be cherry-picked into "develop" branch too :)

**Comment by yashbhutwala** [comment]
interesting, that the helm chart had these images correct.  Although I see a difference between logstash versions, see here: https://github.com/blackducksoftware/hub/blob/master/kubernetes/blackduck-helm/values.yaml#L238

**Comment by operator-r2d2** [comment]
@msenmurugan: once the present PR merges, I will cherry-pick it on top of develop in a new PR and assign it to you.

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/1307#issuecomment-607295127):

>/cherrypick develop


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1307#" title="Author self-approved">msenmurugan</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1307#pullrequestreview-385668946" title="LGTM">yashbhutwala</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/release-2020.2.x/OWNERS)~~ [msenmurugan,yashbhutwala]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yashbhutwala** [comment]
> interesting, that the helm chart had these images correct. Although I see a difference between logstash versions, see here: [blackducksoftware/hub:kubernetes/blackduck-helm/values.yaml@`master`#L238](https://github.com/blackducksoftware/hub/blob/master/kubernetes/blackduck-helm/values.yaml#L238) [](/blackducksoftware/hub/blob/HEAD@{2020-04-01T14:13:42Z}/kubernetes/blackduck-helm/values.yaml#L238)

turns out the helm chart has the incorrect value, but this is fine as 2.x version of the published helm chart is alpha support and not expected to be used much.  this will be fixed in 4.x release of the helm chart.

**Comment by operator-r2d2** [comment]
@msenmurugan: new pull request created: #1308

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/1307#issuecomment-607295127):

>/cherrypick develop


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
