### PR TITLE
Added enable-source-uploads checkbox in webUI

### LINKED ISSUE #416: Allow enabling of Source Code Uploading via check box in UI
**What would you like to be added**:
A checkbox or similar to allow enabling source code uploading when deploying a blackduck instance instead of the user entering a field in the ENV section.

**Why is this needed**:
Ease of use

### PR DESCRIPTION
**Pull request by VSharapov**
Fixes #416

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/434#" title="Author self-approved">VSharapov</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **jdartigalongue**

If they are not already assigned, you can assign the PR to them by writing `/assign @jdartigalongue` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by VSharapov** [comment]
Fixes #415 too

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/434#pullrequestreview-249516635" title="Approved">jdartigalongue</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/434#" title="Author self-approved">VSharapov</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [jdartigalongue]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/434#pullrequestreview-249516635" title="Approved">jdartigalongue</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/434#pullrequestreview-249519721" title="LGTM">rrati</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/434#" title="Author self-approved">VSharapov</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [jdartigalongue,rrati]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rrati** [comment]
@VSharapov Please squash your commits

**Comment by operator-r2d2** [comment]
New changes are detected. LGTM label has been removed.

**Comment by VSharapov** [comment]
Squashed, rebased master, anything else I need to do?
@msenmurugan  I think you're the only pending reviewer

**Comment by yashbhutwala** [comment]
Closing this, opened #454, using the original commit from @VSharapov.

**Pull request closed without merging**
