### PR TITLE
Container Image Tags field self-corrects

### LINKED ISSUE #241: Container Image Tags field is funky
**Describe the bug**
`Container Image Tags`, the field disappears after a backspace.

**To Reproduce**
1. Click on the `Container Image Tags` field
2. Backspace

**Screenshots/additional context**
Screen Shot 2019-04-29 at 9 36 09 AM
Screen Shot 2019-04-29 at 9 36 18 AM

### PR DESCRIPTION
**Pull request by VSharapov**
Fixes #241

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/436#" title="Author self-approved">VSharapov</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **jdartigalongue**

If they are not already assigned, you can assign the PR to them by writing `/assign @jdartigalongue` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yashbhutwala** [comment]
Please also change for [`Environment Variables`](https://github.com/blackducksoftware/synopsys-operator/issues/241#issuecomment-487588988)

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/436#" title="Author self-approved">VSharapov</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/436#pullrequestreview-248823989" title="Approved">yashbhutwala</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [yashbhutwala]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yashbhutwala** [comment]
Just waiting to lgtm if someone else wants to review.

**Comment by msenmurugan** [comment]
@VSharapov Can you pls format the html file? Other than that it is good... Pls check whether environs also have the same issue. I pretty much sure, it will have the same issue.

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/436#pullrequestreview-249510682" title="Approved">jdartigalongue</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/436#" title="Author self-approved">VSharapov</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/436#pullrequestreview-248823989" title="Approved">yashbhutwala</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [jdartigalongue,yashbhutwala]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rrati** [comment]
@VSharapov Please squash your commits and fix for env

**Comment by yashbhutwala** [comment]
Closing this, opened PR #453.

**Pull request closed without merging**
