### PR TITLE
fix memory limits to be expressed as power of two instead of SI unit

### LINKED ISSUE #1087: Use Mi instead of M for memory limits
We are passing `M` to Kubernetes which k8s/kubelet interprets as SI unit (10^6) and then gives it to docker.  However, developers expected to pass to Docker to be `Mi`, meaning binary (2^20).

Lines to fix: 

For SaaS: https://github.com/blackducksoftware/synopsys-operator/blob/saas-2019.8.4/pkg/apps/blackduck/latest/containers/constants.go#L73

For Onprem: https://github.com/blackducksoftware/synopsys-operator/blob/release-2019.11.x/pkg/apps/blackduck/latest/containers/constants.go#L73

**How to reproduce it (as minimally and precisely as possible)**:

`docker run -d --name test-stress -m 2560M polinux/stress stress --vm 1 --vm-bytes 2560M --timeout 10m --verbose`
`docker inspect test-stress`

memory will look like this which is binary ((2**20)*2560)
"Memory": 2684354560

Pass this spec to k8s

```
apiVersion: v1
kind: Pod
metadata:
 name: memory-demo
 namespace: mem-example
spec:
 nodeName: worker0-yashb-2019-10-28-ci-kube1-15-3-1m4w
 containers:
 - name: memory-demo-ctr
 image: polinux/stress
 resources:
 limits:
 memory: "2560M"
 requests:
 memory: "2048M"
 command: ["stress"]
 args: ["--vm", "1", "--vm-bytes", "2460M", "--vm-hang", "1", "--timeout", "10m", "--verbose"]
```

docker inspect <Container Id of the pod> or look at `/sys/fs/cgroup/memory/<PID>/memory.limit_in_bytes`

this will look like this which is SI unit ((10**6)*2560)
"Memory": 256000000

Further details in comments [here](https://jira-sig.internal.synopsys.com/browse/HUB-22114)

**Screenshots/additional context**:
Cross-ref: [HUB-22114](https://jira-sig.internal.synopsys.com/browse/HUB-22114)

[Kubernetes Docs Meaning on Memory](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory)

### PR DESCRIPTION
**Pull request by yashbhutwala**
Fixes #1087 for 12.0 release

- [x] fix memory limits to be expressed as power of two instead of SI unit
- [x] express cpu explicitly in terms of what api takes; 
- [x] improve readability

- [ ] cherry-pick for SaaS

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1100#" title="Author self-approved">yashbhutwala</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [yashbhutwala]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yashbhutwala** [comment]
/hold 

Available for review, but de-prioritize until 11.0 release is out as well as all PRs are sorted.

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1100#pullrequestreview-320169437" title="Approved">msenmurugan</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1100#" title="Author self-approved">yashbhutwala</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [msenmurugan,yashbhutwala]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by operator-r2d2** [comment]
@msenmurugan: new pull request created: #1134

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/1100#issuecomment-562207231):

>/cherrypick release-2019.11.x


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
